# -*- mode:python -*-

Import('*')

SimObject('BranchPredictor.py',
    sim_objects=[
        'BranchPredictor',
        'BranchTargetBuffer',
        'eh2BTB',
        'eh2BHT',
        'ReturnAddrStack',
        # 'EH2BranchPredictor',
    ],
    enums=['BranchType', 'TargetProvider'])

# Keep base BTB implementation because eh2BTB inherits BranchTargetBuffer.
Source('btb.cc')

# EH2 predictor sources.
Source('eh2_pred.cc')
Source('eh2_btb.cc')
Source('eh2_bht.cc')
Source('eh2_ras.cc')

DebugFlag('BTB')
DebugFlag('RAS')
DebugFlag('Branch')